aux_source_directory(. ut_src)
add_library(utils ${ut_src})

target_include_directories(utils PUBLIC ./)
target_link_libraries(utils PUBLIC Vulkan::Vulkan glslang glslang-default-resource-limits glfw glm)
if(APPLE)
  target_compile_definitions(utils PRIVATE VK_USE_PLATFORM_METAL_EXT)
elseif(UNIX)
  target_compile_definitions(utils PRIVATE VK_USE_PLATFORM_XCB_KHR)
elseif(WIN32)
  target_compile_definitions(utils PRIVATE _CRT_SECURE_NO_WARNINGS)
  target_compile_definitions(utils PRIVATE VK_USE_PLATFORM_WIN32_KHR)
endif()